### ISSUE TITLE
Težava pri navajanju osnovne literature z ukazom \plancite{}

### ISSUE THREAD

**Issue by Sega90** [jureslak/magisterij-template#1]
Pozdravljen,

pri navajanju osnovne literature se mi pojavi težava pri deljenju povezav url. Te so precej dolge in se ne delijo na pravem mestu. Težavo sem poskusil rešiti z uporabo:
```
\usepackage{url}
\def\UrlBreaks{\do\/\do-} 
```
Ukaz mi je pomagal deliti povezave v Literaturi, ne pa pri `\plancite{}`.

Lp, Tadej

**Comment by jureslak** [comment]
Živjo, mi daš primer entrya iz `.bib` datoteke, pri katerem se to zgodi?

**Comment by Sega90** [comment]
Živjo, tukaj je primer.
```
@Misc{STtemplate,
  title  = {DRAFT 2016 EU-wide ST templates},
  note   = {[ogled 3.\ 8.\ 2016], dostopno na \url{http://www.eba.europa.eu/documents/10180/1259315/DRAFT+2016+EU-wide+ST+templates.xlsx}},
  key   = {DRAFT 2016 EU-wide ST templates},
}
```
 Sem pa kasneje ugotovil, da se težava pojavi zaradi \begin{itemize} in sem jo uspel rešiti z uporabo `\begin{sloppy}` kot v primeru.
```
\begin{sloppy}
\begin{itemize}
  \plancite{STtemplate}
\end{itemize}
\end{sloppy}
```
Lp, Tadej

**Comment by jureslak** [comment]
Morda lahko namesto `\url` v `note` uporabiš `\href` kot `\href{http://pravilen link.com}{\texttt{link ki ima noter presledke}}`, pa bo link deloval, ko bo prikazan se bo pa zlomil pri presledku, in ne rabiš nobenih dodatnih okolij ali težav. Sicer bom pa pogledal kasneje, v vsakem primeru pa dodam en tak primer noter.

**Comment by jureslak** [comment]
Meni 
```
@Misc{STtemplate,
  title  = {{DRAFT 2016 EU-wide ST templates}},
  note   = {[ogled 3.\ 8.\ 2016], dostopno na \href{http://www.eba.europa.eu/documents/10180/1259315/DRAFT+2016+EU-wide+ST+templates.xlsx}{\texttt{http://\\www.eba.europa.eu/documents/10180/1259315/DRAFT+2016+EU-wide+ST+\\templates.xlsx}}
}
```
deluje ok in je pomoje najlažja rešitev. Sem dodal kot primer za vnaprej.
