### ISSUE TITLE
Težave s citiranjem internetnih strani, ki imajo v naslovu posebne znake (%, #)...

### ISSUE THREAD

**Issue by MijaRazpotnik** [jureslak/magisterij-template#2]
Zdravo!

Primer literature, ki jo želim citirati
```
@Misc{NT,
	title = {Nürnberger Tand},
	note  = {[ogled 23.\ 1.\ 2018], dostopno na \url{https://www.nuernbergwiki.de/index.php/N%C3%BCrnberger_Tand},
}
```
(Problem je verjetno v tem, da je že tu v linku do strani zapis N%C3%BC namesto ü.)

Ko poženem  TexStudio (z ustavljenim `~\cite{NT}`) mi pogosto sploh ne zgenerira pdf-ja.  Včasih mi vendarle ga (nikakor ne morm pogruntat v čem je fora - kdaj mi ga zgenerira in kdaj ne).  V obeh primerih se mi kot error izpiše: Paragraph ended before \BR@c@bibitem was complete.

Če zapis na silo popravim (da namesto N%C3%BC  na roke napišem ü) se pdf datoteka zgenerira brez "errorjev", tudi citiranje deluje. Potem je edini problem, da linki niso aktivni (oziroma ne pripeljejo na pravo stran).

A je še kakšna lepša rešitev te težave?

Mija

**Comment by jureslak** [comment]
Živjo,

problem je samo v tem, da so znaki %, # ipd. za latex rezervirani, potrebno jih je escapat z `\`, torej tvoj url bi se napisalo kot `...index.php/N\%C3\%BCrnberger_Tand`. To tudi ne pokvari linka na stran. 
Sem dodal primer tvojega citata tudi v template. 

Pred ponovnik poskusom ne pozabit počistit dodatnih datotek, ki jih latex naspamma v folder, za to imas v TeXStudiu `Tools > Clean Auxiliary Files`.

Jure

**Comment by MijaRazpotnik** [comment]
Hvala, sedaj dela :)
